export const graphStylesheet = [
  {
    selector: 'node',
    style: {
      'label': 'data(label)',
      'text-valign': 'center',
      'text-halign': 'center',
      'color': '#E6EDF3',
      'font-size': '11px',
      'font-weight': 500,
      'font-family': 'ui-monospace, "JetBrains Mono", "IBM Plex Mono", "Fira Code", monospace',
      'letter-spacing': '0.2px',
      'width': 'label',
      'height': 'label',
      'shape': 'round-rectangle' as const,
      'border-radius': '12px',
      'border-width': 1,
      'border-color': 'rgba(79, 172, 254, 0.45)',
      'padding': '6px 10px',
      'text-wrap': 'wrap' as const,
      'text-max-width': '140px',
      'text-overflow-wrap': 'anywhere' as const,
      'background-color': 'rgba(79, 172, 254, 0.14)',
      'background-opacity': 1,
      'opacity': 0.95,
      'text-outline-width': 0,
      'text-outline-opacity': 0,
      'transition-property': 'opacity, border-width, background-color',
      'transition-duration': '0.15s',
      'transition-timing-function': 'ease-out',
    },
  },
  {
    selector: 'node[type="entry"], node[type="main"]',
    style: {
      'border-width': 2,
      'border-color': 'rgba(79, 172, 254, 0.6)',
      'background-color': 'rgba(79, 172, 254, 0.12)',
      'opacity': 1,
    },
  },
  {
    selector: 'node[type="utility"]',
    style: {
      'opacity': 0.8,
      'background-color': 'rgba(79, 172, 254, 0.1)',
      'border-color': 'rgba(79, 172, 254, 0.35)',
    },
  },
  {
    selector: 'node:selected',
    style: {
      'background-color': 'rgba(79, 172, 254, 0.18)',
      'border-color': 'rgba(79, 172, 254, 0.7)',
      'border-width': 2,
      'opacity': 1,
      'overlay-opacity': 0.08,
      'overlay-color': '#4FACFE',
      'overlay-padding': '4px',
    },
  },
  {
    selector: 'node:hover',
    style: {
      'border-width': 2,
      'border-color': 'rgba(79, 172, 254, 0.7)',
      'opacity': 1,
      'background-color': 'rgba(79, 172, 254, 0.16)',
    },
  },
  {
    selector: 'node.fade',
    style: {
      'opacity': 0.15,
    },
  },
  {
    selector: 'edge',
    style: {
      'width': 1.5,
      'line-color': 'rgba(79, 172, 254, 0.4)',
      'target-arrow-color': 'rgba(79, 172, 254, 0.5)',
      'target-arrow-shape': 'triangle' as const,
      'target-arrow-size': '6px',
      'curve-style': 'bezier' as const,
      'opacity': 0.4,
      'arrow-scale': 1,
      'line-style': 'solid',
      'transition-property': 'opacity, width',
      'transition-duration': '0.15s',
      'transition-timing-function': 'ease-out',
    },
  },
  {
    selector: 'edge[type="primary"]',
    style: {
      'width': 2,
      'opacity': 0.7,
      'line-color': 'rgba(79, 172, 254, 0.6)',
      'target-arrow-color': 'rgba(79, 172, 254, 0.7)',
    },
  },
  {
    selector: 'edge[type="secondary"]',
    style: {
      'width': 1.5,
      'opacity': 0.35,
      'line-color': 'rgba(79, 172, 254, 0.4)',
      'target-arrow-color': 'rgba(79, 172, 254, 0.5)',
    },
  },
  {
    selector: 'edge[type="peripheral"]',
    style: {
      'width': 1,
      'opacity': 0.2,
      'line-color': 'rgba(79, 172, 254, 0.3)',
      'target-arrow-color': 'rgba(79, 172, 254, 0.35)',
    },
  },
  {
    selector: 'edge:selected',
    style: {
      'opacity': 0.7,
      'width': 2,
      'line-color': 'rgba(79, 172, 254, 0.7)',
      'target-arrow-color': 'rgba(79, 172, 254, 0.8)',
    },
  },
  {
    selector: 'edge.highlight-edge',
    style: {
      'opacity': 0.7,
      'width': 2,
      'line-color': 'rgba(79, 172, 254, 0.7)',
      'target-arrow-color': 'rgba(79, 172, 254, 0.8)',
    },
  },
  {
    selector: 'edge.fade',
    style: {
      'opacity': 0.1,
    },
  },
  {
    selector: 'node[id^="ext::"]',
    style: {
      'background-color': 'rgba(100, 116, 139, 0.08)',
      'border-width': 1,
      'border-color': 'rgba(100, 116, 139, 0.35)',
      'border-style': 'solid',
      'opacity': 0.6,
      'color': '#94a3b8',
      'text-outline-width': 0,
      'text-outline-opacity': 0,
      'font-size': '10px',
    },
  },
  {
    selector: 'node[id^="ext::"]:hover',
    style: {
      'border-color': 'rgba(100, 116, 139, 0.5)',
      'opacity': 0.7,
      'background-color': 'rgba(100, 116, 139, 0.12)',
      'color': '#cbd5e1',
    },
  },
  {
    selector: 'node[type="external"]',
    style: {
      'background-color': 'rgba(100, 116, 139, 0.08)',
      'border-width': 1,
      'border-color': 'rgba(100, 116, 139, 0.35)',
      'border-style': 'solid',
      'opacity': 0.6,
      'color': '#94a3b8',
      'text-outline-width': 0,
      'text-outline-opacity': 0,
      'font-size': '10px',
    },
  },
  {
    selector: 'node[type="external"]:hover',
    style: {
      'border-color': 'rgba(100, 116, 139, 0.5)',
      'opacity': 0.7,
      'background-color': 'rgba(100, 116, 139, 0.12)',
      'color': '#cbd5e1',
    },
  },
];
